### PR TITLE
fix: harden against unexpected inputs and fs states

### LINKED ISSUE #22: Use `hasOwnProperty` instead of `in`
https://stackoverflow.com/questions/13632999/if-key-in-object-or-ifobject-hasownpropertykey

### PR DESCRIPTION
**Pull request by marionebl**
* closes #22 
* related: #21

### CODE REVIEW

File: src/cli.ts [hunk 1]
```diff
@@ -196,7 +196,7 @@ async function main(cli: SvgTermCli) {
   const p = guess.profile || "";
   const isFileProfile = ["~", "/", "."].indexOf(p.charAt(0)) > -1;
 
-  if (isFileProfile && "profile" in cli.flags) {
+  if (isFileProfile && "profile" in cli.flags.has) {
```
Comment (adius) [inline src/cli.ts]: That looks wrong
